#!/bin/sh

cd "$(dirname "$0")/../"

source /tmp/rego_venv/.venv/bin/activate
# I didn't find good way how to import file without .py extension.
# Here we add this extension to let us run tests.
ln -s rego rego.py

echo "running tests with: $@"
pytest "$@"

# drop extension again to keep original file without update
rm -f rego.py

# clean all files, generated by test (__pycache__/.coverage),
# except of htmlcov and pytest_cache, which are useful for us
rm -rf .coverage
rm -rf tests/unit/__pycache__
rm -rf __pycache__
